# Generated by Django 3.2.25 on 2025-01-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='STUDENT',
        ),
        migrations.CreateModel(
            name='chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('chat', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
