# Generated by Django 3.2.25 on 2025-01-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250129_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
