# Generated by Django 3.2.25 on 2025-03-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_attendance_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=300)),
                ('condition', models.CharField(max_length=300)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
